version: "3.8"

services:
    postgres:
        image: postgres:15
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: ${POSTGRES_HOST}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    python:
        build: .
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: 5432
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            TARGET_DATE: ${TARGET_DATE}
        volumes:
            - ../../data:/data
            - ./temp:/app/temp
            - ./output:/app/output
            - ./tests:/app/tests
        command: python /app/import_data.py

volumes:
    postgres_data:
